# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.9
  # 版权年份
  copyrightYear: 2024
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: E:/upload
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.iams: debug
    org.springframework: warn

    org.springframework.data.elasticsearch.core: DEBUG
    org.springframework.data.elasticsearch.client.WIRE: TRACE

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  mail:
    host: smtp.qq.com
    port: 465  # 推荐使用SSL加密端口
    username: 1490866637@qq.com  # 发件人邮箱
    password: dqajhzlzsovngeif  # 授权码
    properties:
      mail:
        smtp:
          ssl:
            enable: true  # 启用SSL加密
          auth: true  # 必须开启认证

  activiti:
    database-schema-update: true
    db-history-used: true
    history-level: audit
    check-process-definitions: true
    database-type: postgres

    idm:
      enabled: false
  main:
    allow-bean-definition-overriding: true

  elasticsearch:
    uris: http://localhost:9200
    #uris: http://4e0be009e31d:9200

  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 500MB
      # 设置总上传的文件大小
      max-request-size: 500MB

      enabled: true
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  data:

    # 全文检索
    elasticsearch:
      repositories:
        enabled: true
      rest:
        #uris=4e0be009e31d:9200
        urls: http://localhost:9200

    # redis 配置
    redis:
      # 地址
      #host: redis_iams
      host: localhost
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 0
      # 密码
      password:
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 720

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.iams.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: postgresql
  supportMethodsArguments: true
  params: count=countSql

# Springdoc配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
  group-configs:
    - group: 'default'
      display-name: '测试模块'
      paths-to-match: '/**'
      packages-to-scan: com.iams.web.controller.tool

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

baidu:
  ocr: # OCR服务的配置项
    appId: 117031120 # 百度OCR服务的应用ID
    apiKey: abpi4HQDXDzvP4y8g9EQGS66 # 百度OCR服务的API密钥
    secretKey: 6H7CuD4rVNyD6sOuqZ9NRIGbSVLggN05 # 百度OCR服务的密钥

dromara:
  x-file-storage: #文件存储配置
    default-platform: local-plus-1 #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    #对应平台的配置写在这里，注意缩进要对齐
    local-plus:
      - platform: local-plus-1 # 存储平台标识
        enable-storage: true  #启用存储
        enable-access: true #启用访问（线上请使用 Nginx 配置，效率更高）
        domain: http://127.0.0.1:8080/profile/ # 访问域名，例如：“http://127.0.0.1:8030/file/”，注意后面要和 path-patterns 保持一致，“/”结尾，本地存储建议使用相对路径，方便后期更换域名
        base-path: file/ # 基础路径
        path-patterns: /profile/** # 访问路径
        storage-path: E:/upload/ # 存储路径

minio:
  endpoint: http://127.0.0.1:9000
  accessKey: minio
  secretKey: minio123456
  bucket: iams-main-files
  tempBucket: iams-tmp-files
  certBucket: iams-project-cert

ocr:
  server:
    url: http://OCR_SERVER_IP:PORT/ocr/upload