# 数据源配置
spring:
    elasticsearch:
        #uris: http://4e0be009e31d:9200
        uris: http://localhost:9200
        data:
            elasticsearch:
                repositories:
                    enabled: true

    activiti:
        database-schema-update: true
        db-history-used: true
        history-level: full
        check-process-definitions: true
        database-type: postgres
        idm:
            enabled: false

    main:
        allow-bean-definition-overriding: true

    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        #driverClassName: com.mysql.cj.jdbc.Driver
        #driverClassName: com.kingbase8.Driver
        driverClassName: org.postgresql.Driver


        druid:
            # 主库数据源
            master:
                #                url: jdbc:mysql://localhost:3308/iams?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
                #                username: root
                #                password: 111213172qt
                #
                url: jdbc:postgresql://localhost:5432/iams?currentSchema=iams
                username: postgres
                password: zhld123.

            #                url: jdbc:postgresql://192.168.1.11:5432/iamsdb?productName=PostgreSQL&currentSchema=iams_backend
            #                username: iams
            #                password: zhld123.

            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: false
                url:
                username:
                password:
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置连接超时时间
            connectTimeout: 30000
            # 配置网络超时时间
            socketTimeout: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: select version()
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter:
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username: ruoyi
                login-password: 123456
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true

backup:
    storage-path: /opt/iams/backups/mysql